# Generated by Django 2.0 on 2017-12-22 06:54

import accounts.models.User
from django.db import migrations, models
from accounts.models.User import upload_image_path


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171221_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=upload_image_path),
        ),
    ]
