# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import stores.models.Store
from stores.models.Store import upload_image_path


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='icon',
            field=models.ImageField(null=True, upload_to=upload_image_path),
        ),
    ]
