# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='title',
            new_name='name',
        ),
    ]
