# Generated by Django 2.0 on 2017-12-07 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20171207_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='user',
            field=models.OneToOneField(on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
