# Generated by Django 2.0 on 2018-01-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('vnd', 'VND'), ('usd', 'USD')], default='VND', max_length=50),
        ),
    ]
