# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20171207_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('out-of-stock', 'Out of stock'), ('available', 'Available')], max_length=50),
        ),
    ]
