# Generated by Django 2.0 on 2018-01-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
